spring:
  datasource:
    url: jdbc:h2:mem:incident_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8000


kafka:
  address: "localhost:9092"


market:
  address: "http://localhost:8081"
  dataEndpoint: "/marketData"